# Generated by Django 3.1.6 on 2021-07-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=30)),
                ('g_details', models.CharField(max_length=90)),
                ('g_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_name', models.CharField(max_length=30)),
                ('tasks_details', models.CharField(max_length=90)),
                ('task_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
